import FWCore.ParameterSet.Config as cms

def customizeReRunL1StepForHLTPhase2(process):

    #CRAB hack
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hgcalMergeLayerClusters_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_particleFlow*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_ak4CaloJet*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltEgammaGsfElectron*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_ak4Gen*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_ak8Gen*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_genMet*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_genPU*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltEgammaGsfTracks*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_particleFlowBlock*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_particleFlowCluster*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_displaced*_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_particleFlowSuperCluster*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltHps*_*_HLT')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_slimmedCaloJets_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_slimmedJPTJets_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_gsfTracksOpenConversions_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_ctppsProtons_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_scalersRawToDigi_*_RECO')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltL2MuonFromL1TkMuonCandidates_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltPFMETTypeOne_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltTauPFJets08Region_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltPFPuppiJetForBtagEta2p4_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltAK4*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_pfTICL_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltAK8*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltPFPuppi*_*_HLT')

    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hlt*Filter_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_generalTracks_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltPhase2PixelTracks_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_HGCalRecHit_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_ecalBarrelClusterFastTimer_*_HLT')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_ticlTrackstersMerge_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_prunedTrackingParticles_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_ticlTrackstersCLUE3DHigh_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_MergedMtdTruth*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_MergedTrackTruth_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_MergedCaloTruth_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_EcalRecHits*_HLT')
    
    # More CRAB hacks
    # If your input files have ~1k events, then drop more collections to avoid failing jobs
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_g4SimHits_*_SIM')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1t*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltHoreco_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_horeco_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltCaloMET_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltHtMhtPFPuppiCentralJetsQuadC30MaxEta2p4_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hlt*MuonCandidates_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltEgammaCandidates*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltPhase2PixelVertices_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hlt1PFPuppi*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltBTag*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltDiMuon*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltL3f*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltL1*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_towerMaker_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltHbhereco_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hfprereco_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltHfreco_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hfreco_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_offlinePrimaryVertices_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_offlineBeamSpot_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TriggerResults_*_HLT')

    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TTClusterAssociatorFromPixelDigis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TTStubAssociatorFromPixelDigis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TTTrackAssociatorFromPixelDigis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TTTrackAssociatorFromPixelDigisExtended_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TTStubsFromPhase2TrackerDigis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TTClustersFromPhase2TrackerDigis_*_HLT')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_generator_*_SIM')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_externalLHEProducer_*_SIM')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_generatorSmeared_*_SIM')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_randomEngineStateProducer_*_SIM')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hlt2PFPuppi*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hlt3PFPuppi*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hlt4PFPuppi*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltDouble*_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltTriple*_*_HLT')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltCsc2DRecHits_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltCscSegments_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltDt4DSegments_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltRpcRecHits_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_FTL*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_caloStage2Digis_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_gmtStage2Digis_*_RECO')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_slimmedAddPileupInfo_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_ctppsLocalTrackLiteProducer_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_CSCHaloData_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_offlineBeamSpot_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_BeamHaloSummary_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TriggerResults_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_gtDigis_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_gtStage2Digis_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltL3*_*_HLT')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simKBmtfDigis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simEmtfShowers_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simOmtfDigis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simEmtfDigis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simDtTriggerPrimitiveDigis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simCscTriggerPrimitiveDigis_*_HLT')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simGtStage2Digis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simCaloStage2Digis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simCaloStage2Layer1Digis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simGmtStage2Digis_*_HLT')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_fixedGridRho*_*_RECO')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TriggerResults_*_SIM')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simGmtShowerDigis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simBmtfDigis_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simMuonGEMPadDigiClusters_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simMuonGEMPadDigis_*_HLT')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltSingleAK4PFPuppiJet520_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltTriggerSummaryRAW_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_hltTriggerSummaryAOD_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_fixedGridRhoFastjetAllTmp_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_randomEngineStateProducer_*_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_generatorSmeared_*_HLT')
    
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tTOoLLiPProducer*_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromCombinedCalo*_uncalibrated_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_UncalibratedPhase1L1TJetFromPfCandidates_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromCombinedCalo*_emUncalibrated_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromCombinedCalo*_hcalUncalibrated_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tLayer1*_TK_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tLayer1*_Calo_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tLayer1*_EmCalo_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromCombinedCalo*_hcalUnclustered_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_PuppiRegional_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_L1TkElePerBoard_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_L1TkEmPerBoard_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tLayer1*_PF_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tLayer1*_Puppi_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromCombinedCalo*_ecalCells_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromCombinedCalo*_had_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromCombinedCalo*_egamma_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromCombinedCalo*_em_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tMETMLProducer_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tLayer1*_vec*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tLayer1*_max*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tLayer1*_tot*_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tTrackFastJets_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tTrackTripletEmulation_*_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tTowerCalibration_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tBJetProducerPuppiCorrectedEmulator_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromHGC*_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromCombined*_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPhase2L1CaloEGammaEmulator_*_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tHGCalBackEndLayer1Producer_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tHGCalBackEndLayer2Producer_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tHGCalEnergySplitTowerProducer_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tHGCalTowerProducer_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tHGCalEnergySplitTowerMapProducer_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tHGCalTowerMapProducer_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPFClustersFromL1EGClusters_*_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tHGCalConcentratorProducer_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tHGCalVFEProducer_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TTClusterAssociatorFromPixelDigis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_TTStubAssociatorFromPixelDigis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tBJetProducerPuppi_L1PFBJets_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1t*_DecodedTK_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tEGammaClusterEmuProducer_*_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1*_L1TkEle_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1*_L1TkEm_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*GEMDigis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_L1CaloJetsNoCuts_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*_GCTJet_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_*GEM*_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_gem*_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tCaloJet_L1CaloJetCollectionBXV_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simCaloStage2Digis_*_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simCaloStage2Layer1Digis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simBmtfDigis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simEmtfDigis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simCscTriggerPrimitiveDigis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simDtTriggerPrimitiveDigis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simKBmtfDigis_*_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simGmtStage2Digis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simGmtShowerDigis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simOmtfDigis_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_simEmtfShowers_*_L1TrackTrigger')
    
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tNNCaloTauEmulator_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tLayer1HGCal*_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tLayer1HF_*_L1TrackTrigger')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop *_l1tPhase1JetSumsProducer9x9_*_L1TrackTrigger')

    process.FEVTDEBUGHLToutput.outputCommands.append('drop PixelDigiSimLinkedmDetSetVector_simSiPixelDigis_Tracker_HLT')
    process.FEVTDEBUGHLToutput.outputCommands.append('drop PixelDigiSimLinkedmDetSetVector_simSiPixelDigis_Pixel_HLT')
    #process.FEVTDEBUGHLToutput.outputCommands.append('drop DetIdHGCSampleHGCDataFramesSorted_simHGCalUnsuppressedDigis_EE_HLT')
    

    return process
